### ISSUE TITLE
Create a dummy implementation of ExecutePreparedQuery() in OrientDBBinaryConnection

### ISSUE THREAD

**Issue by weizensnake** [orientechnologies/OrientDB.Net.ConnectionProtocols.Binary#1]
OrientDBBinaryConnection does not implement 

`public IEnumerable<TResultType> ExecutePreparedQuery<TResultType>(string sql, params string[] parameters) where TResultType : OrientDBEntity`

declared in IOrientDatabaseConnection. I understand this is being worked on. In the meantime though this makes it impossibe to connect to any database because the only serializer that exists so far is the CSV serializer which requires OrientDB.Net.Core >= 0.1.16 and so we cannot downgrade to a version of the core library that doesn't blow up this binary protocol implementation.
The symptom of this problem is a TypeLoadException.

I suggest to just add a dummy implementation for ExecutePreparedQuery for the moment so that one can at least use the driver in its current state to connect to a database.

**Comment by alzuma** [comment]
Maybe implementation from abstract class could fix this and in future escape these cross nuget dependencies. 

```
public abstract class OrientDatabaseConnectionBase: IOrientDatabaseConnection {
    public virtual IEnumerable<TResultType> ExecutePreparedQuery<TResultType>(string sql, params string[] parameters) where TResultType : OrientDBEntity
    {
        throw new NotImplementedException();
    }
}
```

then this:
```
public class OrientDBBinaryConnection : IOrientDatabaseConnection, IDisposable
```

to this
```
public class OrientDBBinaryConnection : OrientDatabaseConnectionBase, IDisposable
```

and then just override the methods

If Core nuget changes, adds new method, interface will force to implement it in Base which is located in Core nuget. But changes will not break Protocol nuget with "does not implement" as Base will implement it either with NotImplementedException or real deal.

**Comment by weizensnake** [comment]
Yes I think that could work. Having the interfaces in one project will otherwise always force all dependent projects to upgrade at the same time.

**Comment by mike-echo-oscar-whiskey** [comment]
Shouldn't this be handled with package versioning and dependency constraints?
https://docs.microsoft.com/en-us/nuget/reference/package-versioning

Adding a method to an interface in core means you have a version bump. Existing packages should not take that new version as their dependency.

**Comment by gar-ema** [comment]
Both ways are good choice. As plus, i'm thinking about merging all "core" projects in one solution to help keeping them aligned and publish different nuget packages. Just to boost the development speed instead of waiting for packages publish

**Comment by realityenigma** [comment]
The idea of the Core package is to provide the base interfaces and classes for a modular system. But the idea of keeping everything within a single solution isn't bad idea. I will go ahead and begin moving everything that direction to see if it makes the process easier. Thanks for the suggestions.

**Comment by realityenigma** [comment]
All core projects have been merged here. If everyone is happy with this we can remove the other git repos.

https://github.com/orientechnologies/OrientDB.Net.git

**Comment by alzuma** [comment]
I'm happy 👍 just yesterday started to implement async and it was hell to jump around projects.

**Comment by weizensnake** [comment]
Yes I think that's great and will make working with the projects much easier.

**Comment by alzuma** [comment]
@realityenigma I have feeling that OrientDB.Net.Core in https://github.com/orientechnologies/OrientDB.Net.git is missing last commit. ILogger impl. https://github.com/orientechnologies/OrientDB.Net.Core/commit/a4e2d9f01a53ed0a3b51a00733b5c7342639d382

**Comment by realityenigma** [comment]
@alzuma working on getting it resolved right now.

**Comment by realityenigma** [comment]
@alzuma ILogger changes are now in https://github.com/orientechnologies/OrientDB.Net.git. I also made sure ConnectionsProtocol.Binary implemented the update interface. I am going to close this thread at this point. If you come across any other discrepancies create an issue @https://github.com/orientechnologies/OrientDB.Net.git. Thanks for everyone's help and input, it's much appreciated!
